[project]
name = "linkage-api"
version = "0.1.0"
dependencies = [
  "fastapi",
  "uvicorn",
  "sqlmodel",
  "pandas",
  "recordlinkage",
  "passlib[bcrypt]",
  "python-jose[cryptography]",
  "httpx",
  "python-multipart",
  "pydantic",
  "pytest",
  "rapidfuzz; python_version >= '3.8'",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["app"]
